### ISSUE TITLE
Please add a LICENSE.TXT file

### ISSUE THREAD

**Issue by jfmatth** [S-poony/Ultra-Square-Catcher-USC-#3]
Thank you for this project, it's pretty cool.

Can you add a LICENSE.TXT file so others can fork this and modify.

Thank you.

**Comment by S-poony** [comment]
Thanks for your commit, I added it :)

Le 10 janv. 2019 16:15, "John Flynn Matthew" <notifications@github.com> a
écrit :

**Comment by lovasoa** [comment]
@S-poony : you should close the issue, then.

**Comment by jfmatth** [comment]
Thanks for the update and quick response on the issue.
